#### Stage 1: Build the angular application
FROM node:12.4.0-alpine as build
 
# Configure the main working directory inside the docker image. 
### STAGE 1: Build ###
FROM node:12.7-alpine AS build
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

### STAGE 2: Run ###
FROM nginx:1.17.1-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist/capstone-angular /usr/share/nginx/html